### PR TITLE
fix warpPlayer function for spawn portal

### LINKED ISSUE #150: When warping into map via login or warp command it is not random
When using the `/warp` command or character login the portal is not random.

### PR DESCRIPTION
**Pull request by Hucaru**
Closes #150

### CODE REVIEW

File: channel/handlers.go [hunk 1]
```diff
@@ -1025,20 +1025,9 @@ func (server Server) warpPlayer(plr *Player, dstField *field, dstPortal portal,
 
 	plr.setMapID(dstField.id)
 	plr.pos = dstPortal.pos
-	var spawnIdx byte
 
-	dPortal, err := dstInst.getPortalFromName(dstPortal.name)
```
Comment (Hucaru) [inline channel/handlers.go:1030]: This always returns the first portal as spawn portals all have the name "sp"

Comment (ErwinsExpertise) [reply channel/handlers.go:1030]: Makes sense
