### PR TITLE
bug fixes

### LINKED ISSUE #135: meso magent also working as item pouch
i had a husky with a meso magnet and they were picking up items as well even though i didn't buy the item pouch

### PR DESCRIPTION
**Pull request by ErwinsExpertise**
This PR will resolve #135 and #134

### CODE REVIEW

File: channel/player.go [hunk 1]
```diff
@@ -2065,6 +2065,37 @@ func (p *Player) updatePet() {
 	p.inst.send(packetPlayerPetUpdate(p.pet.sn))
 }
 
+func (p *Player) petCanTakeDrop(drop fieldDrop) bool {
+	if p.pet == nil {
+		return false
+	}
+
+	if drop.mesos > 0 {
+		if p.hasEquipped(1812000) {
```
Comment (Hucaru) [inline channel/player.go]: These should be extracted as mesos magnet and item pouch constants

File: channel/handlers.go [hunk 2]
```diff
@@ -507,16 +525,54 @@ func (server Server) playerPassiveRegen(conn mnet.Client, reader mpacket.Reader)
...
+
+	if healAmount > int16(chair.RecoveryHP) {
+		return
 	}
+
+	if time.Since(plr.lastChairHeal) < 10*time.Second {
+		return
+	}
+
+	plr.giveHP(healAmount)
```
Comment (trameathia) [inline channel/handlers.go:582]: is this actually needed? i swear when i sat in my chair it was already healing me correctly

Comment (ErwinsExpertise) [reply channel/handlers.go:582]: The client automatically shows the HP icon above you, but doesn't actually grant any HP.

File: channel/field.go [hunk 3]
```diff
@@ -549,6 +550,8 @@ type fieldInstance struct {
 	boatType   byte
 	properties map[string]interface{} // this is used to share state between npc and system scripts
 
+	chairs map[int32]int16
```
Comment (Hucaru) [inline channel/field.go]: Redundant map? I can't see where it's used or any reason to store the chair usage in the instance?

File: channel/handlers.go [hunk 4]
```diff
@@ -507,16 +525,54 @@ func (server Server) playerPassiveRegen(conn mnet.Client, reader mpacket.Reader)
...
 func (server Server) playerUseChair(conn mnet.Client, reader mpacket.Reader) {
-	fmt.Println("use chair:", reader)
-	// chairID := reader.ReadInt32()
+	plr, err := server.players.getFromConn(conn)
+	if err != nil {
+		log.Println(err)
+		return
+	}
+	chairID := reader.ReadInt32()
+	plr.chairSit(chairID)
```
Comment (Hucaru) [inline channel/handlers.go]: Does this need to be a plr function? It's only called here and I can't think of any gameplay reason where the player is forced to sit without their input? I ideally prefere keeping as much of the logic together in the handler if possible.

File: channel/handlers.go [hunk 5]
```diff
@@ -507,16 +525,54 @@ func (server Server) playerPassiveRegen(conn mnet.Client, reader mpacket.Reader)
...
-	if reader.ReadInt16() == -1 {
+	plr, err := server.players.getFromConn(conn)
+	if err != nil {
+		log.Println(err)
+		return
+	}
 
-	} else {
+	seatID := reader.ReadInt16()
+	plr.chairResult(seatID)
```
Comment (Hucaru) [inline channel/handlers.go]: Ditto `plr.charSit`

File: channel/player.go [hunk 6]
```diff
@@ -2065,6 +2068,69 @@ func (p *Player) updatePet() {
...
+		it := p.equip[i]
+		if it.slotID < 0 && it.amount > 0 && it.ID == itemID {
+			return true
+		}
+	}
+	return false
+}
+func (p *Player) chairSit(chairID int32) {
+	if chairID <= 0 {
+		delete(p.inst.chairs, p.ID)
```
Comment (Hucaru) [inline channel/player.go]: Not needed? If removed do we need this if statement and the function could be embedded in the handler as
```
	p.chairID = reader.ReadInt32()
	p.inst.send(packetPlayerShowChair(p.ID, p.charID))
	p.Send(packetPlayerChairUpdate())
```

Does the chairID need to be stored as -1? Can't we just use the value the client sends?

File: channel/player.go [hunk 7]
```diff
@@ -2065,6 +2068,69 @@ func (p *Player) updatePet() {
...
+
+	p.chairID = chairID
+	p.inst.send(packetPlayerShowChair(p.ID, chairID))
+	p.Send(packetPlayerChairUpdate())
+}
+
+func (p *Player) chairResult(chairID int16) {
+	if chairID == -1 {
+		if p.chairID != -1 {
+			delete(p.inst.chairs, p.ID)
```
Comment (Hucaru) [inline channel/player.go]: Same comment as function above

File: channel/handlers.go [hunk 8]
```diff
@@ -507,16 +525,62 @@ func (server Server) playerPassiveRegen(conn mnet.Client, reader mpacket.Reader)
...
+	plr, err := server.players.getFromConn(conn)
+	if err != nil {
+		log.Println(err)
+		return
+	}
+
+	chairID := reader.ReadInt32()
+	plr.chairID = chairID
+
+	plr.inst.send(packetPlayerShowChair(plr.ID, chairID))
```
Comment (Hucaru) [inline channel/handlers.go]: Should use and stand skip active plr via `sendExcept(packetPlayerShowChair(plr.ID, chairID), plr.Conn)`?
